function software_auto_complete(selector)
{
	$(selector).autocomplete({
		source: document.software
	});	
}

document.software = [
"Adobe Air",
"Adobe Audition",
"Adobe Bridge",
"Adobe Director",
"Adobe DreamWeaver",
"Adobe FireWorks",
"Adobe Flash Player",
"Adobe Flash Professional",
"Adobe Illustrator",
"Adobe InDesign",
"Adobe Media Encoder",
"Adobe PhotoShop Ext",
"Adobe Reader",
"Adobe Shockwave Player",
"Adobe SVG Viewer",
"AGI-STK Surveys",
"Agisoft PhotoScan (local install)",
"Aladin",
"Alice Programming",
"Alternatiff",
"Amaya",
"Anatomy Lab",
"Anisview",
"Ansys (in Fluent)",
"Ansys (in Fluent)",
"Ansys CFD Viewer",
"Ansys inc Fluent",
"Ape",
"APL-ASRF Mapper",
"Apple iTunes",
"Apple Quicktime",
"Apso",
"Apso",
"Arcady",
"ArcGIS",
"ArcGIS Hydro",
"ArcGIS Productivity Suite",
"ArcView",
"Arduino",
"Aspen ",
"Audacity",
"Audacity",
"AutoCAD",
"Autodesk 3DS Max",
"AutoDesk Architect",
"AutoDesk Architect",
"AutoDesk BackBurner",
"AutoDesk DWG TrueView",
"AutoDesk Inventor Pro",
"AutoDesk MatchMover",
"Autodesk Maya",
"AutoDesk Mechanical",
"AutoDesk Revit",
"AutoDesk Revit",
"AutoDesk Revit",
"Autograph",
"AVR Studio",
"Beam VISAT",
"Beam VISAT",
"Beet",
"Bilko",
"BioEdit",
"Blender",
"BlueJ",
"ByoB",
"C2",
"Cabri 3D",
"Cabri II Plus",
"Cambridge Advanced English Grammar in Use",
"Cambridge Advanced Learner's Dictionary",
"Cambridge Grammar of English",
"Cambridge Pronunciation in Use",
"Camfit",
"CardioLab",
"Caris",
"CATT",
"Cecil",
"Celtx",
"CES EduPack",
"Cgywin",
"Chart & Spirometry",
"ChemBio Draw Ultra",
"Child Development - First Year",
"CityEngine (local install)",
"CLAN",
"Claro Software (ScreenRuler, View, Read)",
"CMAP Tools",
"Cochsim",
"Code Composer Studio",
"CodeBlocks",
"Community Analysis Package",
"Comsol",
"Comsol",
"Comsol",
"Comsol",
"Concise Oxford English Dictionary",
"Confidence Interval Analysis (CIA)",
"ConTEXT",
"Corel Draw",
"Corel Painter",
"Corel Photo-Paint",
"Crystal Maker",
"CSD System Software (CCDC)",
"Cube",
"Cycling Max/MSP (local install)",
"Cyclone",
"Data Viewer",
"Data Viewer",
"DataStream",
"DaVis ",
"DBDesigner 4.0.5.6",
"Depthmap",
"Diagnosys",
"Diamond",
"DietPlan",
"Dillon Videos",
"DJVU",
"DS9",
"EASE - Seminar Skills 2 - Discussions",
"Eclipse",
"EcoPath",
"ECS Drive Mapping (Shortcut)",
"Elica",
"Endnote",
"English Pronunciation in Use Advanced",
"English Pronunciation in Use Intermediate",
"English Vocabulary in Use Advanced",
"English Vocabulary in Use Pre-Intermediate & Intermediate",
"English Vocabulary in Use Upper Intermediate",
"EngWaves",
"Ensight",
"Envi",
"Envi (IDL)",
"Envi (Modis Conversion Toolkit)",
"EPANet",
"Erdas Imagine",
"Erdas Imagine",
"Erdas Imagine",
"Erdas Imagine",
"Euromobil French",
"Euromobil German",
"Euromobil Portuguese",
"Eviews",
"Fathom",
"FD_Test",
"FIlterPro",
"FMSLogo",
"Fortran PowerStation",
"FreeShima",
"Fusion/LDV",
"Gambit",
"Genesis",
"GENIE Climate Simulator",
"Geogebra",
"Geoplot (Term Serv W2003 ONLY)",
"Gepasi",
"GhostScript",
"Ghostscript Viewer",
"Gnuplot",
"Gnuplot",
"Google Chrome",
"Google Earth",
"Google Picasa",
"Google Refine",
"Google SketchUp (Free)",
"Google Sketchup Pro ",
"Gpower",
"GPR Slice",
"Graphpad Prism",
"GravMag",
"Grid Algebra",
"Gridworks",
"Harpoon",
"Hearingloss",
"HEC-RAS",
"HTML Toolkit",
"IBM SPSS ",
"IBM SPSS Amos",
"IBM SPSS Answer Tree",
"IBM SPSS Data Entry",
"IBM SPSS Smart Viewer",
"ID_Test",
"Idrisi",
"Idrisi Selva",
"Imagine Logo",
"Infolytica Elecnet",
"Infolytica Magnet",
"Inspiration",
"Insul",
"InterpOSe",
"IPIX",
"Irfanview",
"Iris",
"Iscape",
"ISVR Intranet (Shortcut)",
"JAGS",
"Java NetBeans",
"JAWS",
"Jmol",
"Jmol",
"Junior Viewpoint",
"Kolor Autopano Giga (local install",
"Kolor Panotour (local install)",
"Kruptos",
"lab Chart Reader (inc spirometry)",
"Labtutor",
"LabTutor",
"LabView",
"LabView",
"LabView",
"Lasergene",
"Lasergene",
"Laterisation",
"Learning Guide Assistant",
"Lectra Kaledo",
"Lightning PLUS Magnifier",
"Linsig",
"Lloyds RuleCalc",
"Lloyds RuleFinder",
"Lloyds SSC",
"Longman Dictionary of Contemporary English",
"LTSpice",
"LUSAS",
"Macmillan English Dictionary",
"Map Explorer",
"Maple",
"Maple",
"Maple",
"Maple Student distribution",
"Maple TA",
"Maple TA Blackboard Plug In",
"Mathematica",
"Mathematica",
"Mathematica",
"Mathematica",
"Mathtype",
"Matlab 32 Bit",
"Matlab 64 Bit",
"MatplotLib (part of Python)",
"MaxSurf",
"Maxwell (local install)",
"Media XW",
"MEGA",
"Melissi",
"Meshlab",
"Microscope (local install)",
"Microscribe (local install)",
"Microsoft Internet Explorer",
"Microsoft Office Professional",
"Microsoft Office Project Professional",
"Microsoft Office Visio Premium",
"Microsoft Producer",
"Microsoft Visual Studio.NET",
"Microsoft Windows 7 Enterprise 64 bit",
"Microsoft Windows Live Call",
"Microsoft Windows Live Messenger",
"Microsoft Windows Live Movie Maker",
"Microsoft Windows Live Photo Gallery",
"Microsoft Windows Live Writer",
"Microsoft Windows Media Player",
"MikTeX (2.9)+TexMaker(3.02)",
"MikTeX (2.9)+TexNicCentre(RC1)",
"Mindjet MindManager",
"Minitab",
"Minolta Scanning softeware (local install)",
"MLlWin",
"MLwiN",
"Mozilla Firefox",
"Mplus Demo",
"MSC Nastran",
"MSC Patran",
"MSW logo",
"Multispec",
"Net Op",
"Neurosim (local install)",
"No Machine Player",
"NotePAD++ (inc. NPPtoR)",
"NotePad++ (inc. NPPtoR)",
"NPZ Visualizer",
"Nutri Survey",
"Nvivo",
"NX Client",
"Oasys Alp",
"Oasys Frew",
"Oasys GSA",
"Oasys Pdisp",
"Oasys Pile",
"Oasys Safe",
"Oasys Slope",
"Oasys Xdisp",
"Ocean Data View",
"Octave",
"Oilfield Data Manager",
"Omnigraph",
"Omnipage",
"Openbugs",
"OpenText Exceed",
"Origin",
"Origin",
"Origin",
"Origin",
"Origin",
"Oscady Classic",
"Oscady Pro",
"Oxford Learner's Thesaurus",
"Oxford Practice Grammer Advanced Practice Boost",
"Oxford Practice Grammer Intermediate Practice",
"Palisade @Risk",
"Panopto",
"PAST",
"Petrel",
"Photoscan",
"Phys Models - BioPhys",
"Phys Models - Phys1d",
"Phyto_1d",
"PicoScope",
"Pinch Int- (inc. Water-Int (v1.1) and Heat Int(v1.4))",
"Pointools Suite",
"PointWise",
"Polygon Workbench (local install)",
"PostGIS (local install)",
"PowerSim",
"Praat",
"Practice Navigator",
"Pratt",
"Pre-Sessional Software (Desktop Shortcut)",
"President for a Day",
"Primer",
"Processing",
"PS - Power and Sample Size Calculation",
"PsychoPy",
"Pure Data Extended",
"PuTTY",
"Py6s",
"Python (XY) / Enthought Python",
"Q-Pulse",
"QGIS +Spearfish and Grass",
"QGIS +Spearfish and Grass",
"QStatLab",
"Questionmark (Perception/Secure)",
"Quincy",
"QVT Term",
"R (64 Bit) + Rstudio (0.95)",
"RapidForm (local install)",
"Read Up Speed Up",
"Realplayer",
"Reaxys Online",
"Reference Manager",
"Relex (PTC Windchill)",
"Res2div",
"Reshaper 3D (local install)",
"Rhino and grasshopper (local install)",
"RTI Builder and RTI Viewer",
"S-Plus (Tibco Spotfire)",
"SAMS",
"SAS",
"SAS",
"SAS",
"SAS",
"SAS Enterprise Guide",
"SAS Enterprise Guide",
"SAS Enterprise Guide",
"SAS Enterprise Guide",
"SAS Enterprise Miner",
"SAS Enterprise Miner",
"SAS Enterprise Miner",
"SAS Enterprise Miner",
"SAS JMP",
"SAS JMP",
"SAS JMP",
"SAS JMP",
"SBAS",
"SciFinder",
"Scope",
"Scratch MIT",
"Scratch MIT",
"Screencast-O-Matic",
"Second Life",
"sfs2sfhed",
"Ship Design",
"SigmaPlot (inc, SigmaStat)",
"SigmaStat",
"Simul8",
"Sketchpad",
"SmartBoard",
"Snap Survey",
"Sniffy Pro",
"SolidWorks",
"Soundscriber",
"Spartan",
"Speech Filing System ",
"Spelling Fusion",
"SPSS Sample Power",
"SSH Secure Shell",
"Star-CCM+ with StarWorks",
"StarLogo TNG",
"Stata IC",
"Stata IC",
"Stata SE",
"Stata SE",
"Statistics for the Terrified",
"Stella",
"Stellarium",
"StereoWin",
"Streaming Speech",
"Surfer",
"SymyxDraw",
"Tanner Tools L-Edit",
"Tecplot 360",
"Textease Studio CT",
"TextHelp Read and Write",
"The Sky Pronounciation Suite",
"Tortoise HG",
"Traverso-DAW",
"TSA_Data_Gui",
"Turning Point",
"TypeIT",
"UCINET (local install)",
"UKESCC Earth Science Courseware",
"Unity 3D",
"Vanguard Studio",
"Vanguard Studio Help",
"Viewpoint",
"Visual - TM",
"Visual MODFlow",
"Visual Molecular Dynamics",
"Visual Paradigm",
"Visual Quantum Mechanics.",
"Visual Spec",
"Visual Thesaurus",
"VLC Media Player",
"Vocabulary Builder",
"Voyager",
"Vray (local install)",
"Vue Xstream",
"WebbIE",
"Wimba Create",
"WinAVR",
"WinBUGS",
"WinEdt",
"WinEdt",
"WinEdt",
"WinEdt",
"WinRiver",
"WinX13 Arima",
"Wolfson Software",
"Xmlspy",
"XpressIVE MP",
"Xray",
"Zorba",
"Zotero"
]
